#!/bin/bash

AR_CATKIN_ROOT=$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)

# Catkin workspace alias
alias AR_catkin_source="source ${AR_CATKIN_ROOT}/ar_environment.sh"
alias AR_catkin_delete="rm -r ${AR_CATKIN_ROOT}/devel ${AR_CATKIN_ROOT}/build ${AR_CATKIN_ROOT}/logs"
alias AR_catkin_clean="catkin clean --yes"
alias AR_catkin_build="catkin build"
alias AR_catkin_cd="cd ${AR_CATKIN_ROOT}"

# Missions
alias AR_simulator="roslaunch sim_common sim.launch"
alias AR_simulator_gui="roslaunch sim_common sim.launch gui:=true"
alias AR_pipeline="roslaunch project_interface node_pipeline.launch"

# Files
AR_map_file="${AR_CATKIN_ROOT}/src/0_mindstorm_simulator/2_lego_world/models/mindstorm_map/map.sdf"
AR_interface_dir="${AR_CATKIN_ROOT}/src/9_project_interface/include"
AR_config_dir="${AR_CATKIN_ROOT}/src/9_project_interface/config"

# RVIZ Launching
# alias AR_rviz="roslaunch fsd_common_meta rviz_trackdrive.launch"

# RQT_multiplot Launch
# alias AR_plot_dt=

