#!/bin/bash

AR_CATKIN_ROOT=$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)

# catkin workspace alias
alias AR_catkin_source="source ${AR_CATKIN_ROOT}/ar_environment.sh"
alias AR_catkin_delete="rm -r ${AR_CATKIN_ROOT}/devel ${AR_CATKIN_ROOT}/build ${AR_CATKIN_ROOT}/logs"
alias AR_catkin_clean="catkin clean --yes"
alias AR_catkin_build="catkin build"
alias AR_catkin_cd="cd ${AR_CATKIN_ROOT}"

# catkin workspace alias
alias AR_source="source ${AR_STUDENT_ROOT}/environment.sh"
alias AR_build="cd ${AR_STUDENT_ROOT} && rm -r build && mkdir build && cd build && cmake .."
alias AR_make="cd ${AR_STUDENT_ROOT}/build && make"
alias AR_cd="cd ${AR_STUDENT_ROOT}"

# Missions
#alias AR_launch_sim="roslaunch fsd_common_meta trackdrive.launch"
#alias AR_launch_sim_pipeline="roslaunch fsd_common_meta trackdrive.launch"

# RVIZ Launching
#alias AR_rviz="roslaunch fsd_common_meta rviz_trackdrive.launch"

# RQT_multiplot Launch
#alias AR_plot_dt=

alias AR_logo='\
printf "       \e[32m++++++ Applied Robotics  ++++++\n" && \
printf "       |\e[34m                             \e[32m|\n" && \
printf "       |\e[34m           \_\               \e[32m|\n" && \
printf "       |\e[34m          (_**)              \e[32m|\n" && \
printf "       |\e[34m         __) #_              \e[32m|\n" && \
printf "       |\e[34m        ( )...()             \e[32m|\n" && \
printf "       |\e[34m        || | |I|             \e[32m|\n" && \
printf "       |\e[34m        || | |()__/          \e[32m|\n" && \
printf "       |\e[34m        /\(___)              \e[32m|\n" && \
printf "       |\e[34m       _-\"\"\"\"\"\"\"-_\"\"-_       \e[32m|\n" && \
printf "       |\e[34m       -,,,,,,,,- ,,-        \e[32m|\n" && \
printf "       \e[33mTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT\n\n\e[0m" '

